services:
  asngenerator:
    image: asngenerator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      ASN_NAMESPACE_RANGE: 50
      ASN_PREFIX: WBD