name: deno-asn-generator

services:
  app:
    image: asngenerator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    env_file:
      - .env
    environment:
      ASN_NAMESPACE_RANGE: 50
      ASN_PREFIX: WBD
      ASN_BARCODE_TYPE: CODE128